### PR TITLE
fix main field typo in package.json

### PR DESCRIPTION
**Pull request by EbrahimKreem**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
no it's actually an extension for old ES5 style code - commonjs or vanillajs

read it here: https://dev.to/iggredible/what-the-heck-are-cjs-amd-umd-and-esm-ikm

**Comment by atherdon** [comment]
that files generated by rollupjs, you can check that configuration at rollup.cfg.js

**Comment by EbrahimKreem** [comment]
> that files generated by rollupjs, you can check that configuration at rollup.cfg.js
I know it is generated by rollup but in the dist folder it generated as index.cjs and it is not a valid javascript file

**Comment by EbrahimKreem** [comment]
Screenshot from 2019-09-14 22-49-33

**Comment by atherdon** [comment]
then it should be updated at rollup as well

**Comment by atherdon** [comment]
just to be clear:

rollup cfg updates
1) updated inside of the root of this repository
2) update at projects3.0

3) update package.json for each project at projects3.0
4) push changes here

**Comment by EbrahimKreem** [comment]
after the changes ->

Screenshot from 2019-09-15 09-23-28

**Comment by atherdon** [comment]
ok, cool - waiting for commit with changes at rollup and will merge this PR

**Comment by EbrahimKreem** [comment]
as I read the rollup docs there is no need to update the rollup.cfg.js because we are taking the value of the output file from package.json
https://github.com/GroceriStar/food-datasets-csv-parser/blob/6f6d4eeab3756588fa0b1e71a1d9b2a72fc376e9/rollup.config.js#L13

https://github.com/GroceriStar/food-datasets-csv-parser/blob/6f6d4eeab3756588fa0b1e71a1d9b2a72fc376e9/rollup.config.js#L97

**Comment by atherdon** [comment]
you right
i forget how we setup that. merging

do the same thing at https://github.com/GroceriStar/sd, https://github.com/GroceriStar/food-static-files-generator, https://github.com/GroceriStar/groceristar-fetch as well.
maybe it also solves some of our issues

**Pull request merged**
