### PR TITLE
code linting and formating fixes

### PR DESCRIPTION
**Pull request by EbrahimKreem**

### CODE REVIEW

**Comment by EbrahimKreem** [comment]
I noticed that Airbnb style requires a single quote and our .prttierrc requires doubly quote so I change it to a single quote do suggest to keep it as it is or change the eslint rule to doubly quote?

**Comment by atherdon** [comment]
> I noticed that Airbnb style requires a single quote and our .prttierrc requires doubly quote so I change it to a single quote do suggest to keep it as it is or change the eslint rule to doubly quote?

if now it work - i'm fine with it :) just want to move forward

**Comment by atherdon** [comment]
And please also fix this error: https://travis-ci.org/GroceriStar/food-datasets-csv-parser/jobs/574228641#L481

other issues we'll address a bit later

**Comment by EbrahimKreem** [comment]
> Can you also move configuration that we have at rollup.config.js into /projects3.0/* - there we have 3 places where we need rollup as well.
before it has an outdated configuration. So i delete it. in the root right now we have latest config version

you mean that I should copy rollup inside every folder there or just in the root

**Comment by atherdon** [comment]
you should open rollup.config.js from the root.
and move it(not just copy) into 3 folders at `projects3.0` folder

**Comment by atherdon** [comment]
just a quick note - dont delete next time a PR template. it's better to fill it with details - so anyone can quickly understand what your feature is about

**Comment by atherdon** [comment]
tell me if i should merge this PR and then you'll create a new one with next changes.
Just want to move forward and clean up PR tab

**Comment by EbrahimKreem** [comment]
I think it's better to merge this PR and then I will create a new one with my next changes.

**Comment by atherdon** [comment]
all right

**Pull request merged**
