### PR TITLE
lint and format code before any commit

### PR DESCRIPTION
**Pull request by EbrahimKreem**
created a ".prettierrc" file same as "groceristar-fetch/.prettierrc" and enabled lint-staged for linting and formatting code before any commit

### CODE REVIEW

**Comment by atherdon** [comment]
merging, but want to move lint-staged and probably husky setup into `*.config.js` 
check setup at https://github.com/GroceriStar/food-static-files-generator

**Comment by atherdon** [comment]
we have a problems with your current changes.

**Comment by EbrahimKreem** [comment]
what are the problems?

**Comment by atherdon** [comment]
as code was not perfected - we have a lot of eslint errors - that preventing me from commiting new changes. tried to fix that lint issues - but got tired :).
So i want to disable lint-staged, in order to push my code to github, and then, you can enable it again, but also will be forced to fix all eslint errors

**Comment by EbrahimKreem** [comment]
yes I know about this and I forgot to ask you about it in my perspective it's a good feature and it will force all contributors to perfect their code before committing but it's tiring so I think it's good to make it off in this time and fix eslint errors as we progress in this module

**Comment by EbrahimKreem** [comment]
yeah I know about this the problem is "eslint --fix" is not Automatically fixing eslint errors so, in my opinion, it's good to leave it off in this time

**Comment by atherdon** [comment]
for me it's a perfect feature. anything that improving code and add things automatically without man`s personal input is definately awesome.

for now i'll disable what you've done - commit my code and then you'll be able to create a separated branch/PR where you'll be able to make it work completely

**Comment by atherdon** [comment]
I push my changes to our repository - you can start to work on your
changes + eslint fixes that was left

>

**Pull request merged**
