### PR TITLE
corrected paths for src/USFA/

### PR DESCRIPTION
**Pull request by AndrewSerra**
related to issue #33 about paths

### CODE REVIEW

**Comment by AndrewSerra** [comment]
I'll check FoodComposition now. What should I do for the paths to sd then?

**Comment by AndrewSerra** [comment]
I converted FoodComposition/csv_parser.js to ES6 style, I don't know what to do with paths, I assume they connect to sd but what would the path be? @atherdon

**Comment by atherdon** [comment]
show me the code please

**Comment by atherdon** [comment]
about paths - we'll do it soon. just want to make you know about them

**Comment by AndrewSerra** [comment]
okay I'll open PR then for the ES6 style in FoodComposition

**Pull request merged**
