### PR TITLE
made a copy of getHeader.js and converted to ES6

### PR DESCRIPTION
**Pull request by AndrewSerra**
This is a pull request for issue #56 

**Changes**
1. Copy of `getHeader.js` is made. New copy name is `getHeaderCopy.js`
2. Changed `getHeaderCopy.js` to ES6 style

### CODE REVIEW

**Comment by atherdon** [comment]
what is `csvtojson`? I don't remember that we have such module

**Comment by atherdon** [comment]
@AndrewSerra tell me if you need help with it

**Comment by AndrewSerra** [comment]
> what is `csvtojson`? I don't remember that we have such module

Sorry I have been a bit MIA for a while. I have been busy with school-related stuff and I have a hard time to work on these even though they are quick fixes. Sending the update now. Again sorry for the delay

**Comment by atherdon** [comment]
not a problem at all. i just was confused what i should do with this PR.
reviewing it

**Pull request merged**
