### PR TITLE
test `getHeaders` function inside projects2.0/FAO/Fish folder

### PR DESCRIPTION
**Pull request by EbrahimKreem**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
should I merge this code changes or wait a bit

**Comment by EbrahimKreem** [comment]
> should I merge this code changes or wait a bit 

I think we should wait until @zhangted PR merges and discuss what to do next

**Comment by atherdon** [comment]
I merged @zhangted PR, but not sure if those changes breaking your PR.

Ted, let's chat here what we're doing next

**Comment by zhangted** [comment]
> I merged @zhangted PR, but not sure if those changes breaking your PR.
> 
> Ted, let's chat here what we're doing next
What file do you think is suitable for working on? Also, can you make a video on how to run the program? I have not been able to compile and tinker with the whole program yet.

**Comment by atherdon** [comment]
@zhangted did you check this issue before. it contains a lot of information. check it and if something will be not clear - tell me: https://github.com/GroceriStar/food-datasets-csv-parser/issues/100

at this moment Ebrahim trying to make proejcts2.0 folder with csv files inside to make work.
i'm working on projects3.0 and also on separated generator module

**Comment by EbrahimKreem** [comment]
ok @atherdon please merge this PR to avoid conflicts with @zhangted latest changes

**Comment by atherdon** [comment]
ok, great, reviewing it now

**Pull request merged**
