### PR TITLE
Added FAO dataset and parser

### PR DESCRIPTION
**Pull request by SyeedHasan**
### Changes Made:

- Added individual parsers along with dataset
- Fixed a looping bug 

Pleas let me know more about the build process so I can try fixing the issues at csvToJson.

### CODE REVIEW

**Comment by SyeedHasan** [comment]
Reverted the commit from yesterday. 
I've less experience with babel. I know this might be a beginner question but. I ran these commands:
`npm run build`
`npm run build:babel`

It created the files in the dist directory. I tried executing individual parsers but they raise the EcmaScript errors I tried to fix. I'll look more into how this works myself.

**Comment by atherdon** [comment]
main script that we're using is `npm run build` -it's generate a cool version of code using rollupjs module. it's similar to webpack, but for small modules.
`npm run build:babel` it's an old version of setup that i keeping for some reasons. Sometimes it's easy to debug code by running babel compiler only. but it's a deprecated stuff.

> I tried executing individual parsers but they raise the EcmaScript errors I tried to fix. I'll look more into how this works myself.

not sure what do you mean. install loom for chrome and make a video - maybe your doing it not correctly. this module is not mature yet, so as you can see - we have "confusing" spots here

**Comment by atherdon** [comment]
i'm ready to merge it, but check codeclimate report https://codeclimate.com/github/GroceriStar/food-datasets-csv-parser/pull/114

**Comment by SyeedHasan** [comment]
> Looks awesome!
> Is it really works, i.e. after running scripts - it actually generate static json files?

Don't merge it yet. I would like to build and test before you do it. There's still the issue of the files being generated under the USFA folder.

**Comment by SyeedHasan** [comment]
> main script that we're using is `npm run build` -it's generate a cool version of code using rollupjs module. it's similar to webpack, but for small modules.
> `npm run build:babel` it's an old version of setup that i keeping for some reasons. Sometimes it's easy to debug code by running babel compiler only. but it's a deprecated stuff.
> 
> > I tried executing individual parsers but they raise the EcmaScript errors I tried to fix. I'll look more into how this works myself.
> 
> not sure what do you mean. install loom for chrome and make a video - maybe your doing it not correctly. this module is not mature yet, so as you can see - we have "confusing" spots here

Okay let me make a video tonight so you can see my view.

**Comment by atherdon** [comment]
cool. waiting then

>

**Comment by SyeedHasan** [comment]
https://www.loom.com/share/5e9d6e9c48f2477581770f5ddac9ed5d

Can you please help me? Here's the error I'm facing.

**Comment by atherdon** [comment]
will check it soon

**Comment by atherdon** [comment]
watched

**Comment by atherdon** [comment]
https://www.loom.com/share/f12bc979c28d4fd687a4ee0b466bdc42

**Comment by atherdon** [comment]
We made some changes with team, and it affected some of files that you worked with as well.
please pull changes from main repository and sync with upstream.
if you will need more details how to do it - tell me.

it should solve a merge conflict for that file

**Comment by SyeedHasan** [comment]
I'll fetch from the upstream. I did it once before. I'll do it once I code.
Thanks for the video. It's a little clarifying. Still, if it was possible for me to test my CSV files and convert them into JSON, that would be great. I'll explore the code and see other TODO's too.

**Comment by atherdon** [comment]
Let's split it into small tasks.
first thing will be to merge this PR into main code base. then you can jump to the next thing.
Did you roll back your ES5 changes that you've made in our files?

**Comment by SyeedHasan** [comment]
Yes, I reverted that commit successfully. And continued with ES6 only.

**Comment by atherdon** [comment]
hold on.

**Comment by atherdon** [comment]
i'm checking if code at your PR don't cause any errors with prev changes

**Comment by atherdon** [comment]
OK, looks like first changes done - please open a new PR, even empty where well talk about next changes.
I just spotted a confusion, related to `getHeader` method - will try to check it in a few hours

and if you made some changes from this PR - i'll also be able to view them and give some feedback

**Comment by atherdon** [comment]
i'm working on basic files from `src` folder - so if you need something - tell me.
Or if you made some changes - show them so i can understand what to do next

**Pull request merged**
