### PR TITLE
Fao changes

### PR DESCRIPTION
**Pull request by atherdon**
## Proposed changes

My goal is to show @SyeedHasan changes that i've made in order to fix errors that we had before.
For sure, when this PR will be merged - all forked versions should be synced.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
And when I'm running a parser, I got this error.
So i think now we have another issue, and it's related to headers stuff

image

**Comment by SyeedHasan** [comment]
I'll be using the same template from now on @atherdon

**Comment by SyeedHasan** [comment]
Let me pull the changes and see to it.

**Comment by atherdon** [comment]
you can click on commits tab here and explore that commits

**Comment by atherdon** [comment]
i want to merge this changes into master - tell me when you'll check commits so i can move it forward

**Comment by SyeedHasan** [comment]
> i want to merge this changes into master - tell me when you'll check commits so i can move it forward

I should just check them right now? I'm available for a few hours so working on this right now.

**Comment by SyeedHasan** [comment]
> > i want to merge this changes into master - tell me when you'll check commits so i can move it forward
> 
> I should just check them right now? I'm available for a few hours so working on this right now.

I'll fix the codeclimate reviews

**Comment by SyeedHasan** [comment]
Screenshot from 2019-08-25 21-41-18
Line 27 is still configured to work with USFA dataset only. Can we discuss this next?

**Comment by atherdon** [comment]
let's do it this way - i'm merging this PR, then will open a new one, where
we'll talk about updates, related to `csvToJson` method

>

**Comment by SyeedHasan** [comment]
Sounds good.

**Pull request merged**
