### PR TITLE
writes json file successfully now

### PR DESCRIPTION
**Pull request by zhangted**
## Proposed changes

Writes json file when running 'node parser.js' from a directory with a csv file in it. But csv files are largely empty. 

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

#125

### CODE REVIEW

**Comment by atherdon** [comment]
can you re-sync your branch, because now your PR has conflicts

**Comment by atherdon** [comment]
Ted tell me if you need help with sync process.
I also don't remember if I shared with you some of my courses, related to git - it can help you with our workflow a bit

**Comment by atherdon** [comment]
I just ran `yarn csv:fish_reftbl`
image

i assume it can be because of un-sync at your branch

**Comment by atherdon** [comment]
i'll resolve conflicts for now, but next time i'll show how to do it automatically

**Comment by zhangted** [comment]
hmm why does the line 
   ` at Object.<anonymous> (C:\Users\tedcb\Documents\GitHub\food-datasets-csv-parser\node_modules\@groceristar\static-data-generator\dist\index.cjs.js:810:13)`
cause problems now?

**Comment by zhangted** [comment]
Running `node parser.js` from a valid folder in powershell doesn't work now... I dont get it. It was working before..?

**Comment by zhangted** [comment]
Also, the fullPath variable is no longer used in the updated read stream code bit, so the assign/generate functions are never called

**Comment by zhangted** [comment]
Also, in fileSystem.js, a new variable has to be assigned to the the fullPath, idk exactly why but it gives null indexes otherwise:
`var fileInfo = file.split('.'); // => ['name', 'type']
      var fullPath = [directoryPath, fileInfo[0], fileInfo[1]];
      console.log("Current inquiry:", fullPath[0], fullPath[1], fullPath[2]);
      if (fullPath[2] === 'csv') {
        csvToJson(fullPath, headers);`

**Comment by atherdon** [comment]
i cannot replicate your errors without seeing exact code at PR :)
not a robot with nodejs debugger at my head. create pr, put code and explain step by step what i should do in order to receive issues like you have, similar to questions - not clear at all at this moment

**Comment by zhangted** [comment]
> i cannot replicate your errors without seeing exact code at PR :)
> not a robot with nodejs debugger at my head. create pr, put code and explain step by step what i should do in order to receive issues like you have, similar to questions - not clear at all at this moment

My bad. So when I run `node parser.js` from a valid folder, I get this error now (https://i.imgur.com/Cm43SoT.png)

**Comment by atherdon** [comment]
are you still using old way to call parser, or you using `yarn csv:xxx`?
it's better to use the second one. because it will show me how to replicate
it.  i just want to create it on my side.

And I really don't like `node parser` approach.


Looks like utils from one of the modules is not connected...

1. Was it works before?
2. Can you also confirm that you sync your fork with changes from our main
repository-master branch and also re-install the packages?

I made some small changes at master branch, and also merged changes from
Ebrahim, so it will be cool if you sync with them.

**Comment by zhangted** [comment]
1. Yeah it was working before, but the json files were empty/filled with null information.
2. I reinstalled a couple of times. I run bundle, build, and then try the csv:___ commands. I still get the same error (missing utils)

**Comment by atherdon** [comment]
Ok, tell me how I can replicate the same error.

Maybe you can use Loom extension for chrome and shoot a simple video - because it's still not clear how i can see it on my local PC

**Comment by atherdon** [comment]
you branch is not up-to-date, please run sync.

again, if you don't know how to do it - let me know

**Comment by zhangted** [comment]
Okay,I just synced it. Here is a video showing the error: https://www.loom.com/share/d03b47e5796241d7b3adecd1b8532fbe

Maybe we should roll back my changes and I will try to redo them on top of Ebrahim's PR.

**Comment by atherdon** [comment]
will check video later busy now
1) sync
2) try to fix it

>

**Pull request merged**
