### PR TITLE
Feature/issue13

### PR DESCRIPTION
**Pull request by AndrewSerra**
Almost all functions were connected in cccsvparser, so I removed parseDirectoryFiles and put it in fileSystem.js 

Another change is the added functions in utils.js This will allow having functions easier to read.

### CODE REVIEW

**Comment by AndrewSerra** [comment]
> need to check it deeply. i have feeling that it will break things

In what way? The function I wrote in utils.js or separation of the files? I wrote a test to check if the function worked and it did, but of course, it wasn't an extensive test.

**Comment by atherdon** [comment]
It's just hard for me to procced it quickly.
will need more time.

Did you push that test to this PR as well?

**Comment by atherdon** [comment]
**note 1**
Can you do a similar thing at our code base, so we'll grab less code into our module? when we import the whole library - it got imported
https://github.com/GroceriStar/food-static-files-generator/blob/master/src/utils.js#L9
https://github.com/GroceriStar/food-static-files-generator/blob/master/src/fileSystem.js#L4

**Comment by AndrewSerra** [comment]
no I did not push the test. And I'll do the other request.

**Comment by AndrewSerra** [comment]
Should I push the test for joinPath function that I wrote as well?

**Comment by atherdon** [comment]
**note2**
at generator code we updated a code a bit, in order to make it lighter.
see what i meen

``` writeInFile.writeFile(combinedPath), data);```

was updated: 
https://github.com/GroceriStar/food-static-files-generator/blob/master/src/generateFile.js#L1 
https://github.com/GroceriStar/food-static-files-generator/blob/master/src/generateFile.js#L18

yes, you can publish that test here

**Comment by atherdon** [comment]
you can also find some errors in your changes if you run `yarn build:babel`

**Comment by AndrewSerra** [comment]
We're you saying this error :) 
```
{ SyntaxError: /Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/src/CCCSVParser.js: Unexpected token, expected ";" (21:43)

  19 |   // we can also create a method for path.join, so it wouldn't complicate our code
  20 |   // really bad line
> 21 |   writeInFile.writeFile(combinedPath), data);
     |                                            ^
  22 | }
  23 | 
  24 | const splitJsonIntoFiles = (fileName) => {
    at Parser.raise (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:6325:17)
    at Parser.unexpected (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:7642:16)
    at Parser.semicolon (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:7624:40)
    at Parser.parseExpressionStatement (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:10364:10)
    at Parser.parseStatementContent (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:9963:19)
    at Parser.parseStatement (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:9829:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:10405:25)
    at Parser.parseBlockBody (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:10392:10)
    at Parser.parseBlock (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:10376:10)
    at Parser.parseFunctionBody (/Users/andrew/Desktop/GroceriStar/food-datasets-csv-parser/node_modules/@babel/parser/lib/index.js:9424:24)
  pos: 844,
  loc: Position { line: 21, column: 43 },
  code: 'BABEL_PARSE_ERROR' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by atherdon** [comment]
not sure, is this a question?

**Comment by AndrewSerra** [comment]
> you can also find some errors in your changes if you run `yarn build:babel`

I thought that was the error you were talking about, I fixed that and now it builds.

**Comment by atherdon** [comment]
i don't see fix without commits to this PR ;)

**Comment by atherdon** [comment]
ok checking it right now

**Comment by atherdon** [comment]
#13

**Pull request merged**
