### PR TITLE
Removed import/export of getHeaders and moved mainWrapper to a differ…

### PR DESCRIPTION
**Pull request by sibasish14**
## Proposed changes
It fixes the issue https://github.com/GroceriStar/food-datasets-csv-parser/issues/180. The following changes were made:
1. Moved the `mainWrapper` method to a separate file `mainWrapper.js`
2. Now, since `getHeaders` was not used directly anywhere, it's import/export has been removed from `index.js`. Although, `getHeaders` is still being imported in `mainWrapper.js` because the `mainWrapper` method uses `getHeaders`

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by EbrahimKreem** [comment]
in future, we will use `mainWrapper` in parsers to reduce duplicates

**Comment by atherdon** [comment]
awesome suggestion!

>

**Comment by sibasish14** [comment]
@EbrahimKreem Do you mean I should remove all the comment lines? Or do you mean I should copy the contents of the `Main()` in `mainWrapper`? Or do you mean something else?

**Comment by EbrahimKreem** [comment]
comment all the code inside `mainWrapper` and copy the contents of `Main()`

**Comment by sibasish14** [comment]
I have made the changes.
I have some questions though:
1. Should I replace `Fish_Reftbl_RefDatasets.csv` (line 32) with `directory + filename` where `directory = './'`. Otherwise I think it'll work only for a particular dataset.
2. Now, since, the `mainWrapper()` and the `Main()` have the same code (and thus I think they shoud work the same), why do we have different name?

**Comment by EbrahimKreem** [comment]
> Should I replace Fish_Reftbl_RefDatasets.csv (line 32) with directory + filename where directory = './'. Otherwise I think it'll work only for a particular dataset.

the problem is when we use the directory var the context will be the `src/` folder and this will make `Error: ENOENT: no such file or directory` when reading CSV files

so to avoid this you can add a second argument called `dirPath` to `mainWrapper` method and this will solve the problem

**Comment by sibasish14** [comment]
OK. I will do that. And so the changes would be:
- Line 6: `const mainWrapper = async (filename, dirPath) => {`
- Line 32: `const directoryPath = path.join(dirPath, filename);`
- Line 34: `await csvToJson(dirPath, data);`

Am I right?

**Comment by EbrahimKreem** [comment]
yes

**Comment by atherdon** [comment]
we have a build error here, but I tend to merge this PR

**Pull request merged**
